(function(){
'use strict';
const STORE='tianyu-learning-v4',SECRET='tianyu-sync-code-v1',DEVICE='tianyu-device-v1',API='https://szmgavbpablkyninbftu.supabase.co/functions/v1/tianyu-sync';
const KEYS={technical:'tianyu-error-notebook-2026-10-03-v1',practical:'tianyu-practical-notebook-v1'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const copy=x=>JSON.parse(JSON.stringify(x));function canonical(v){if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));return v}const same=(a,b)=>JSON.stringify(canonical(a))===JSON.stringify(canonical(b));
let device,doc={schema:4,cells:{}},code='',tick=Date.now(),dirty=false,inflight=false,timer,status='本机保存',lastSync='',applying=false;
const adapters=new Map(),lastSnapshots={};
try{device=localStorage.getItem(DEVICE)||crypto.randomUUID();localStorage.setItem(DEVICE,device);doc=valid(JSON.parse(localStorage.getItem(STORE)||'null'))||doc;code=localStorage.getItem(SECRET)||''}catch{device=crypto.randomUUID();status='本机保存不可用'}
function valid(d){if(!d||d.schema!==4||!d.cells||typeof d.cells!=='object'||Array.isArray(d.cells))return null;const cells={};for(const [k,c] of Object.entries(d.cells)){if(k.length>200||!c||typeof c.clock!=='string'||!/^\d{16}-[\w-]+$/.test(c.clock))continue;cells[k]=c;tick=Math.max(tick,Number(c.clock.slice(0,16)))}return {schema:4,cells}}
function stamp(){tick=Math.max(Date.now(),tick+1);return String(tick).padStart(16,'0')+'-'+device}
function merge(a,b){const result=copy(a);for(const [k,c] of Object.entries(b.cells)){const old=result.cells[k];if(!old||c.clock>old.clock)result.cells[k]=copy(c);if(old&&k.endsWith('/current')&&old.value!==c.value){const subject=k.split('/')[0],ma=a.cells[subject+'/round/'+old.value+'/meta']?.value,mb=b.cells[subject+'/round/'+c.value+'/meta']?.value;if((ma?.startedAt||'')>(mb?.startedAt||''))result.cells[k]=copy(old);else if((ma?.startedAt||'')<(mb?.startedAt||''))result.cells[k]=copy(c);}if(old&&(/\/(?:baseline|seen|complete)\//.test(k))&&old.value>c.value)result.cells[k]={value:old.value,clock:old.clock>c.clock?old.clock:c.clock}}return result}
function get(k,fallback){return doc.cells[k]?.value??fallback}
function set(k,v){if(same(get(k),v))return false;doc.cells[k]={value:copy(v),clock:stamp()};dirty=true;return true}
function save(){try{const stored=valid(JSON.parse(localStorage.getItem(STORE)||'null'));if(stored)doc=merge(doc,stored);localStorage.setItem(STORE,JSON.stringify(doc));return true}catch{status='保存失败，请保持页面打开';paintStatus();return false}}
function isShort(id){return /^p\d+-2[6-8]$/.test(id)}
function partCount(id){return /-28$/.test(id)||id==='p3-27'?5:4}
function capture(subject,env,bank,legacy=false){if(!env)return;const s=env.session,prior=lastSnapshots[subject]?.session,sameRound=!!prior&&!!s?.roundId&&prior.roundId===s.roundId;
 if(!get(subject+'/baselineReady',false)){for(const [id,n] of Object.entries(env.wrongCounts||{})){set(subject+'/baseline/'+id,n);if(n>0&&!id.includes(':')){set(subject+'/seen/'+id,true);set(subject+'/complete/'+id,true)}}set(subject+'/baselineReady',true)}
 if(!s?.ids?.length)return;
 s.roundId=s.roundId||'r-'+crypto.randomUUID();const r=s.roundId,base=subject+'/round/'+r;
 if(legacy&&!get(base+'/initial',null))set(base+'/initial',{counted:!!s.statsRecorded,grades:s.selfGrades||{}});
 if(!get(base+'/initial',null))set(base+'/initial',{counted:false,grades:{}});
 const initial=get(base+'/initial');
 const metadata={...s};delete metadata.answers;delete metadata.selfGrades;
 const previous=get(base+'/meta',null);if(previous?.submitted&&!metadata.submitted)metadata.submitted=true;
 const oldMeta=prior?{...prior}:null;if(oldMeta){delete oldMeta.answers;delete oldMeta.selfGrades}if(!sameRound||!same(oldMeta,metadata))set(base+'/meta',metadata);
 const current=get(subject+'/current',null),other=current?get(subject+'/round/'+current+'/meta',null):null;
 if(!current||current===r||!other||(s.startedAt||'')>=(other.startedAt||''))set(subject+'/current',r);
 for(const id of s.ids){const a=s.answers?.[id]||[],short=isShort(id),parts=short?partCount(id):0;
  if(short){for(let i=0;i<parts;i++)if(!sameRound||a[i]!==prior.answers?.[id]?.[i])set(base+'/answer/'+id+':'+i,typeof a[i]==='string'?a[i]:'');for(let i=0;i<parts;i++){const grade=s.selfGrades?.[id]?.[i]||null;if(!sameRound||grade!==(prior.selfGrades?.[id]?.[i]||null))set(base+'/grade/'+id+':'+i,grade);if(s.submitted&&a[i]?.trim()&&(grade||initial.grades[id]?.[i]||get(subject+'/count/'+id+':'+(i+1)+'/'+r)!==undefined)){const orig=initial.counted&&initial.grades[id]?.[i]==='review'?1:0;set(subject+'/count/'+id+':'+(i+1)+'/'+r,(grade==='review'?1:0)-orig)}}}
  else {if(!sameRound||!same(a,prior.answers?.[id]||[]))set(base+'/answer/'+id,Array.isArray(a)?a:[]);if(s.submitted&&!initial.counted&&a.length&&bank){const q=bank.questions.find(q=>q.id===id);if(q)set(subject+'/count/'+id+'/'+r,[...a].sort().join(',')===[...q.answer].sort().join(',')?0:1)}}
  const touched=short?a.some(v=>v?.trim()):a.length>0,completed=short?a.length>=parts&&a.slice(0,parts).every(v=>v?.trim()):a.length>0;
  if(touched)set(subject+'/seen/'+id,true);if(completed)set(subject+'/complete/'+id,true);
 }
 lastSnapshots[subject]=copy(env);
}
function counts(subject){const result={};for(const [k,c] of Object.entries(doc.cells)){if(k.startsWith(subject+'/baseline/'))result[k.slice((subject+'/baseline/').length)]=c.value;}
 for(const [k,c] of Object.entries(doc.cells)){if(k.startsWith(subject+'/count/')){const id=k.slice((subject+'/count/').length).split('/')[0];result[id]=(result[id]||0)+(Number(c.value)||0)}}for(const k of Object.keys(result))result[k]=Math.max(0,result[k]);return result}
function snapshot(subject){const r=get(subject+'/current',null),meta=r?get(subject+'/round/'+r+'/meta',null):null;if(!meta)return {schema:2,session:null,wrongCounts:counts(subject)};
 const s=copy(meta),base=subject+'/round/'+r;s.answers={};s.selfGrades={};
 for(const id of s.ids){if(isShort(id)){s.answers[id]=Array.from({length:partCount(id)},(_,i)=>get(base+'/answer/'+id+':'+i,''));s.selfGrades[id]=Array.from({length:partCount(id)},(_,i)=>get(base+'/grade/'+id+':'+i,null));}else s.answers[id]=get(base+'/answer/'+id,[])}
 return {schema:2,session:s,wrongCounts:counts(subject)};
}
function writeEnvelopes(){for(const subject of Object.keys(KEYS)){if(!get(subject+'/current'))continue;try{localStorage.setItem(KEYS[subject],JSON.stringify(snapshot(subject)))}catch{status='本机保存失败'}}}
function apply(){writeEnvelopes();applying=true;try{for(const [subject,a] of adapters){const snap=snapshot(subject);if(a.apply(snap)!==false)lastSnapshots[subject]=copy(snap)}}finally{applying=false}paintStatus();paintPortal()}
function record(subject,env,bank){if(applying)return;capture(subject,env,bank);save();writeEnvelopes();queue()}
function progress(subject,id){return get(subject+'/complete/'+id,false)?'已做':get(subject+'/seen/'+id,false)?'部分填写':'未做'}
function flag(subject,id){return !!get(subject+'/flag/'+id,false)}
function note(subject,id){return get(subject+'/note/'+id,'')}
function edit(subject,id,text){set(subject+'/note/'+id,text);const saved=save();queue();return saved}
function toggle(subject,id){set(subject+'/flag/'+id,!flag(subject,id));save();queue();return flag(subject,id)}
function totals(subject,ids){return {done:ids.filter(id=>progress(subject,id)==='已做').length,partial:ids.filter(id=>progress(subject,id)==='部分填写').length,flags:ids.filter(id=>flag(subject,id)).length,total:ids.length}}
function bytes64(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
function from64(str){return Uint8Array.from(atob(str),c=>c.charCodeAt(0))}
async function key(){return crypto.subtle.importKey('raw',Uint8Array.from(atob(code.replace(/-/g,'+').replace(/_/g,'/')+'='),c=>c.charCodeAt(0)),{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function auth(){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode('tianyu-auth:'+code));return Array.from(new Uint8Array(h),b=>b.toString(16).padStart(2,'0')).join('')}
async function encrypt(d){const iv=crypto.getRandomValues(new Uint8Array(12)),data=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(),new TextEncoder().encode(JSON.stringify(d)));return {version:1,iv:bytes64(iv),data:bytes64(new Uint8Array(data))}}
async function decrypt(enc){if(!enc)return {schema:4,cells:{}};const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:from64(enc.iv)},await key(),from64(enc.data));const d=valid(JSON.parse(new TextDecoder().decode(raw)));if(!d)throw new Error('invalid_state');return d}
function queue(){clearTimeout(timer);if(code)timer=setTimeout(()=>sync(),1000);paintStatus()}
async function request(method,body){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(API,{method,headers:{'X-Notebook-Key':await auth(),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:controller.signal,cache:'no-store'});const data=await r.json();return {ok:r.ok,status:r.status,data}}finally{clearTimeout(timeout)}}
async function sync(){if(!code||inflight||document.visibilityState==='hidden')return;inflight=true;status='正在同步';paintStatus();try{
 for(let retry=0;retry<4;retry++){
  const remote=await request('GET');if(!remote.ok)throw new Error(remote.status===401?'invalid_code':'cloud_unavailable');
  const cloud=await decrypt(remote.data.encrypted),before=JSON.stringify(doc);doc=merge(doc,cloud);save();if(JSON.stringify(doc)!==before)apply();
  if(same(doc,cloud)){dirty=false;status='已同步';lastSync=new Date().toLocaleTimeString('zh-CN',{hour12:false});break}
  const sending=copy(doc),encrypted=await encrypt(sending),sent=await request('PUT',{revision:remote.data.revision,encrypted});
  if(sent.status===409)continue;if(!sent.ok)throw new Error('cloud_unavailable');
  dirty=!same(doc,sending);status=dirty?'等待同步':'已同步';lastSync=new Date().toLocaleTimeString('zh-CN',{hour12:false});apply();break;
 }
 if(status==='正在同步'){status='等待同步';dirty=true}
 }catch(e){status=e.message==='invalid_code'?'同步链接无效':'离线，等待同步';dirty=true}finally{inflight=false;paintStatus();if(dirty&&code){clearTimeout(timer);timer=setTimeout(()=>sync(),5000)}}}
function personalLink(){const root=new URL(location.pathname.includes('/technical/')||location.pathname.includes('/practical/')?'../':'./',location.href);root.search='';root.hash='sync='+code;return root.href}
function connect(value){let next=String(value).trim();try{if(next.includes('#'))next=new URL(next).hash.slice(1).replace(/^sync=/,'')}catch{}if(!/^[A-Za-z0-9_-]{43}$/.test(next))return false;code=next;localStorage.setItem(SECRET,code);location.hash='sync='+code;dirty=true;paintStatus();sync();return true}
function paintStatus(){document.querySelectorAll('[data-sync-status]').forEach(el=>el.textContent=code?status+(status==='已同步'&&lastSync?' '+lastSync:''):'仅本机保存');document.querySelectorAll('a#subject-link,a#technical,a#practical').forEach(a=>{if(code){const u=new URL(a.href,location.href);u.hash='sync='+code;a.href=u.href}});const link=document.getElementById('sync-link');if(link)link.value=code?personalLink():'';const desc=document.getElementById('sync-description');if(desc)desc.textContent=code?'同一个专属链接在手机和电脑打开后，会自动同步。链接绑定你的记录，请只在自己的设备间分享。':'打开你的专属同步链接即可连接两台设备，不需要账号。';}
function paintPortal(){for(const [subject,target,total] of [['technical','tech-resume',194],['practical','prac-resume',35]]){const el=document.getElementById(target);if(!el)continue;const ids=Object.keys(doc.cells).filter(k=>k.startsWith(subject+'/complete/')).map(k=>k.split('/').pop());el.textContent=`累计已做 ${ids.length} / ${total} 题`+(get(subject+'/current')?' · 有练习记录':'')}}
function dialogs(){if(document.getElementById('sync-dialog'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="sync-dialog"><div class="dialog-top"><h2>跨设备同步</h2><button id="close-sync">关闭</button></div><p id="sync-description"></p><p data-sync-status role="status"></p><label for="sync-link">你的专属同步链接</label><input id="sync-link" readonly autocomplete="off"><div class="actions"><button id="copy-sync">复制同步链接</button><button id="force-sync">立即同步</button></div><label for="connect-link">连接已有同步链接</label><input id="connect-link" autocomplete="off" placeholder="粘贴专属链接或同步码"><button id="connect-sync">连接同步</button><p class="small" id="sync-message"></p></dialog><dialog id="records-dialog"><div class="dialog-top"><h2>题目记录</h2><button id="close-records">关闭</button></div><div class="record-filters"><button data-record-filter="all">全部</button><button data-record-filter="unseen">未做</button><button data-record-filter="flag">疑问</button><button data-record-filter="noted">有笔记</button></div><div id="record-list"></div></dialog><dialog id="note-dialog"><div class="dialog-top"><h2 id="note-title">我的笔记</h2><button id="close-note">关闭</button></div><textarea id="note-editor" rows="10" placeholder="记录你的理解、疑问和记忆方法…"></textarea><p class="small" id="note-status" role="status">输入自动保存</p></dialog>`);
 document.getElementById('close-sync').onclick=()=>document.getElementById('sync-dialog').close();document.getElementById('close-records').onclick=()=>document.getElementById('records-dialog').close();document.getElementById('close-note').onclick=()=>document.getElementById('note-dialog').close();
 document.getElementById('copy-sync').onclick=async()=>{if(!code){document.getElementById('sync-message').textContent='请先打开专属同步链接。';return}try{await navigator.clipboard.writeText(personalLink());document.getElementById('sync-message').textContent='链接已复制，发送到自己的另一台设备即可。'}catch{document.getElementById('sync-link').select();document.getElementById('sync-message').textContent='请长按上方链接复制。'}};
 document.getElementById('force-sync').onclick=()=>sync();document.getElementById('connect-sync').onclick=()=>{document.getElementById('sync-message').textContent=connect(document.getElementById('connect-link').value)?'已连接，正在同步。':'链接格式不正确。'};
}
function initUI(){dialogs();const h=document.querySelector('.appbar-inner')||document.querySelector('header');if(h&&!document.getElementById('sync-button')){h.insertAdjacentHTML('beforeend','<button class="sync-button" id="sync-button"><span data-sync-status>仅本机保存</span></button>');document.getElementById('sync-button').onclick=()=>{paintStatus();document.getElementById('sync-dialog').showModal()}}paintStatus();paintPortal()}
function openNote(subject,id,label){dialogs();const e=document.getElementById('note-editor');document.getElementById('note-title').textContent=label+' · 我的笔记';e.value=note(subject,id);e.oninput=()=>{document.getElementById('note-status').textContent=edit(subject,id,e.value)?'已自动保存 · '+(code?'等待同步':'仅本机'):'保存失败，请保持页面打开'};document.getElementById('note-dialog').showModal()}
function records(subject,bank,onPractice){dialogs();const d=document.getElementById('records-dialog');let filter='all';function render(){const qs=bank.questions.filter(q=>filter==='all'||filter==='unseen'&&progress(subject,q.id)!=='已做'||filter==='flag'&&flag(subject,q.id)||filter==='noted'&&note(subject,q.id));document.getElementById('record-list').innerHTML=qs.map(q=>`<div class="record-row"><div><strong>第${q.paper}套 · 原题${q.number}</strong><p class="small">${progress(subject,q.id)}${flag(subject,q.id)?' · ★ 疑问':''}${note(subject,q.id)?' · 有笔记':''}</p></div><button data-record-practice="${q.id}">作答</button><button data-record-note="${q.id}">笔记</button></div>`).join('')||'<p class="small">没有符合条件的题目。</p>';d.querySelectorAll('[data-record-practice]').forEach(b=>b.onclick=()=>{d.close();onPractice([b.dataset.recordPractice])});d.querySelectorAll('[data-record-note]').forEach(b=>b.onclick=()=>{const q=bank.questions.find(q=>q.id===b.dataset.recordNote);openNote(subject,q.id,`第${q.paper}套原题${q.number}`)})}d.querySelectorAll('[data-record-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.recordFilter;render()});render();d.showModal()}
function homePanel(subject,bank,onPractice){if(document.querySelector('.learning-dashboard'))return;const t=totals(subject,bank.questions.map(q=>q.id));document.getElementById('app').insertAdjacentHTML('afterbegin',`<section class="learning-dashboard"><h2>我的学习记录</h2><p>累计已做 <strong>${t.done}</strong> · 未完整作答 <strong>${t.total-t.done}</strong>${t.partial?`（部分填写 ${t.partial}）`:''} · 疑问 <strong>${t.flags}</strong></p><div class="learning-actions"><button id="practice-unseen">练习未做题</button><button id="practice-flags" ${t.flags?'':'disabled'}>练习疑问题</button><button id="view-records">查看题目记录</button></div><p class="small" data-sync-status></p></section>`);document.getElementById('practice-unseen').onclick=()=>onPractice(bank.questions.filter(q=>progress(subject,q.id)!=='已做').map(q=>q.id));document.getElementById('practice-flags').onclick=()=>onPractice(bank.questions.filter(q=>flag(subject,q.id)).map(q=>q.id));document.getElementById('view-records').onclick=()=>records(subject,bank,onPractice);paintStatus()}
function flagButton(subject,id){return `<button class="flag-button" data-flag-id="${id}" aria-pressed="${flag(subject,id)}">${flag(subject,id)?'★ 已标记疑问':'☆ 标记疑问'}</button>`}
function bindFlags(subject){document.querySelectorAll('[data-flag-id]').forEach(b=>b.onclick=()=>{adapters.get(subject)?.cancelAuto?.();const yes=toggle(subject,b.dataset.flagId);b.setAttribute('aria-pressed',String(yes));b.textContent=yes?'★ 已标记疑问':'☆ 标记疑问'})}
function quizPanel(subject,id){const top=document.querySelector('.quiz-top');if(top&&!document.querySelector('.quiz-mark'))top.insertAdjacentHTML('afterend',`<div class="quiz-mark">${flagButton(subject,id)}<span class="small">标记不会影响作答和判分</span></div>`);bindFlags(subject)}
function navPanel(subject,ids){const grid=document.getElementById('nav-grid');for(const b of [...grid.querySelectorAll('button[data-index]')]){const id=ids[Number(b.dataset.index)],wrap=document.createElement('div');wrap.className='nav-item';b.replaceWith(wrap);wrap.append(b);b.classList.toggle('flagged',flag(subject,id));b.setAttribute('aria-label',b.getAttribute('aria-label')+(flag(subject,id)?'，已标记疑问':''));wrap.insertAdjacentHTML('beforeend',`<button class="nav-flag" data-flag-id="${id}" aria-label="标记第${Number(b.dataset.index)+1}题疑问" aria-pressed="${flag(subject,id)}">${flag(subject,id)?'★ 疑问':'☆ 疑问'}</button>`)}bindFlags(subject);grid.querySelectorAll('.nav-flag').forEach(b=>{const original=b.onclick;b.onclick=()=>{original();b.closest('.nav-item').querySelector('[data-index]').classList.toggle('flagged',flag(subject,b.dataset.flagId))}});document.getElementById('navigator').querySelector('.legend').textContent+=' 星标表示有疑问，可随时标记或取消。'}
function noteHTML(subject,id,label){return `<div class="my-note"><label for="note-${id}">${esc(label)}</label><textarea id="note-${id}" data-note-id="${id}" rows="4" placeholder="写下自己的理解、疑问、记忆方法…">${esc(note(subject,id))}</textarea><p class="small note-save" role="status">${note(subject,id)?'已保存':'输入自动保存'}</p></div>`}
function reviewPanel(subject,qs){document.querySelectorAll('.review-card').forEach((card,i)=>{const q=qs[i];if(!q)return;card.insertAdjacentHTML('beforeend',`<div class="review-mark">${flagButton(subject,q.id)}</div>`+noteHTML(subject,q.id,'我的笔记（这道题的总记录）'));if(isShort(q.id))card.querySelectorAll('.short-review').forEach((part,j)=>part.insertAdjacentHTML('beforeend',noteHTML(subject,q.id+':'+(j+1),'第'+(j+1)+'小问笔记')))});bindFlags(subject);document.querySelectorAll('[data-note-id]').forEach(e=>e.oninput=()=>{e.closest('.my-note').querySelector('.note-save').textContent=edit(subject,e.dataset.noteId,e.value)?'已自动保存 · '+(code?'等待同步':'仅本机保存'):'保存失败，请保持页面打开'})}
function register(subject,a){adapters.set(subject,a);const initial=a.read();capture(subject,initial,a.bank,true);save();writeEnvelopes();const snap=snapshot(subject);if(a.apply(snap)!==false)lastSnapshots[subject]=copy(snap);initUI();queue()}
window.Tianyu={record,register,snapshot,counts,progress,flag,note,totals,same,homePanel,quizPanel,navPanel,reviewPanel,openNote,sync,connect,get applying(){return applying},get status(){return status},get doc(){return copy(doc)},merge,encrypt,decrypt};
// Import the current envelopes once, preserving legacy cumulative counts without inventing missing past correct answers.
for(const subject of Object.keys(KEYS)){try{const raw=JSON.parse(localStorage.getItem(KEYS[subject])||'null'),env=raw?.schema===2?raw:raw?{session:raw,wrongCounts:{}}:null;if(env)capture(subject,env,null,true)}catch{}}
save();writeEnvelopes();
const fromLink=location.hash.match(/^#sync=([A-Za-z0-9_-]{43})$/)?.[1];if(fromLink)connect(fromLink);else if(code){history.replaceState(null,'',location.pathname+location.search+'#sync='+code);queue()}
window.addEventListener('hashchange',()=>{const next=location.hash.match(/^#sync=([A-Za-z0-9_-]{43})$/)?.[1];if(next&&next!==code)connect(next)});
window.addEventListener('storage',e=>{if(e.key===STORE){const remote=valid(JSON.parse(e.newValue||'null'));if(remote){doc=merge(doc,remote);apply();queue()}}});window.addEventListener('online',()=>sync());window.addEventListener('focus',()=>sync());document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')sync()});setInterval(()=>{if(code)sync()},20000);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initUI);else initUI();
})();
