(function(){
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),KEYS={technical:'tianyu-error-notebook-2026-10-03-v1',practical:'tianyu-practical-notebook-v1',consolidation:'tianyu-consolidation-notebook-v1'};
let bank,selection=[],pdfFile,objectUrl,scanResult,scannedBank,fileHash='',busy=false,loadingBank=false,loadRevision=0,lastSelectionKey='';
const banks=new Map();
async function bankFor(subject){if(!['technical','practical','consolidation'].includes(subject))throw Error('PDF科目识别信息不匹配，请重新导出。');if(!banks.has(subject)){const r=await fetch(subject+'.json');if(!r.ok)throw Error('题库加载失败，请联网打开或更新完整离线下载。');banks.set(subject,await r.json())}return banks.get(subject)}
function local(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}}
function paperValue(){return document.querySelector('input[name=paper]:checked')?.value||'all'}
function controlState(){for(const el of document.querySelectorAll('input[name=paper],#kind,#scope,#format'))el.disabled=loadingBank||busy||!bank;$('subject').disabled=busy;$('export').disabled=loadingBank||busy||!selection.length}
function updateSelection(){controlState();if(!bank)return;const subject=$('subject').value,env=local(KEYS[subject],{}),session=env.schema===2?env.session:env,counts=Tianyu.counts(subject),cells=local('tianyu-learning-v4',{}).cells||{},scope=$('scope').value;
 selection=bank.questions.filter(q=>(paperValue()==='all'||String(q.paper)===paperValue())&&($('kind').value==='all'||($('kind').value==='short')===(q.type==='short'))&&(scope==='all'||scope==='current'&&session?.ids?.includes(q.id)||scope==='wrong'&&(counts[q.id]>0||Object.keys(counts).some(id=>id.startsWith(q.id+':')&&counts[id]>0))||scope==='flag'&&cells[subject+'/flag/'+q.id]?.value));
 const key=[bank.subject,paperValue(),$('kind').value,$('scope').value,$('format').value,selection.map(q=>q.id).join(',')].join('|');if(lastSelectionKey&&key!==lastSelectionKey&&!busy&&!$('download').hidden){$('download').hidden=true;$('export-status').textContent='导出条件已更改，请重新生成PDF。'}lastSelectionKey=key;const name=paperValue()==='all'?'全部套卷':'第'+paperValue()+'套',choices=selection.filter(q=>q.type!=='short').length;$('selection').textContent=name+' · '+`共 ${selection.length} 道题：选择题 ${choices} 道，案例 ${selection.length-choices} 道。`+(scope!=='all'?'范围来自已保存的学习记录（含PDF作答）。':'');$('export').disabled=busy||!selection.length;
}
async function changeSubject(){const revision=++loadRevision,subject=$('subject').value;loadingBank=true;bank=null;selection=[];$('download').hidden=true;$('retry-bank').hidden=true;$('selection').className='small';$('selection').textContent='正在加载题库，请稍候…';controlState();try{const loaded=await bankFor(subject);if(revision!==loadRevision)return;bank=loaded;if(!Array.isArray(bank.questions))throw Error('题库格式不完整，请重新加载。');const ids=[...new Set(bank.questions.map(q=>Number(q.paper)).filter(Number.isInteger))].sort((a,b)=>a-b),saved=local('tianyu-pdf-paper-v1',{})[subject],value=ids.some(id=>String(id)===saved)?saved:'all';$('paper-options').innerHTML=[{id:'all',title:'全部套卷'},...ids.map(id=>({id:String(id),title:bank.papers?.find(p=>Number(p.id)===id)?.title||'第'+id+'套'}))].map(p=>{const count=bank.questions.filter(q=>p.id==='all'||String(q.paper)===p.id).length;return `<label class="paper-choice"><input type="radio" name="paper" value="${p.id}" ${p.id===value?'checked':''}><span>${esc(p.title)}<small>${count} 道题</small></span></label>`}).join('');document.querySelectorAll('input[name=paper]').forEach(input=>input.onchange=()=>{try{const saved=local('tianyu-pdf-paper-v1',{});saved[subject]=input.value;localStorage.setItem('tianyu-pdf-paper-v1',JSON.stringify(saved))}catch{}updateSelection()});$('kind').value='all';$('kind').querySelector('[value=short]').disabled=subject!=='practical';loadingBank=false;const url=new URL(location.href);url.searchParams.set('subject',subject);history.replaceState(null,'',url.pathname+url.search+url.hash);updateSelection()}catch(e){if(revision!==loadRevision)return;loadingBank=false;bank=null;selection=[];$('selection').textContent=e.message;$('selection').className='error';$('retry-bank').hidden=false;controlState()}}
let libPromise;function library(){if(!libPromise)libPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='vendor/pdf-lib.min.js';s.onload=resolve;s.onerror=()=>{libPromise=null;reject(Error('PDF工具加载失败，请联网打开或重新下载完整离线题库。'))};document.head.append(s)});return libPromise}
function progress(id){return (done,total,stage)=>{$(id).textContent=stage+' '+done+' / '+total+'…'}}
async function exportPdf(){if(busy||!selection.length)return;const exportQuestions=selection,exportSubject=bank.subject,exportPaper=paperValue(),withSolutions=$('format').value==='solutions';busy=true;updateSelection();$('export-status').className='';$('download').hidden=true;try{await library();const {bytes,manifest}=await PdfNotebook.makePdf({questions:exportQuestions,subject:exportSubject,solutions:withSolutions,onProgress:progress('export-status')});if(objectUrl)URL.revokeObjectURL(objectUrl);const name=(exportSubject==='technical'?'安全技术':exportSubject==='consolidation'?'技术巩固':'其他安全实务')+'-'+(exportPaper==='all'?'选定题目':'第'+exportPaper+'套')+'-'+manifest.id.slice(0,8)+'.pdf';pdfFile=new File([bytes],name,{type:'application/pdf'});objectUrl=URL.createObjectURL(pdfFile);$('download-pdf').href=objectUrl;$('download-pdf').download=name;$('download').hidden=false;$('export-status').textContent=`已生成 ${manifest.totalPages} 页 · ${(bytes.length/1048576).toFixed(1)} MB。题目与答题框均已放入 PDF。`;$('share-pdf').hidden=!navigator.canShare?.({files:[pdfFile]});}catch(e){$('export-status').className='error';$('export-status').textContent=e.message||'生成失败，请重试。'}finally{busy=false;updateSelection()}}
function paintPending(){const pending=scanResult.rows.filter(r=>!r.confirmed).length;$('pending').textContent=pending?`${pending} 道题需要确认后才能批改。`:'识别结果已就绪，可以核对后批改。';$('grade').disabled=pending>0||busy}
function renderRows(){const byId=new Map(scannedBank.questions.map(q=>[q.id,q]));$('rows').innerHTML=scanResult.rows.map((r,i)=>{const q=byId.get(r.id);return `<div class="pdf-row" data-row="${i}"><h4>第${q.paper}套 · 原题${q.number} · ${q.type==='single'?'单选':'多选'}</h4><p class="small">${esc(q.stem)}</p><img src="${r.crop}" alt="第${q.paper}套第${q.number}题实际答题框"><div class="pdf-choices">${Object.keys(q.options).map(letter=>`<label><input type="checkbox" data-row="${i}" value="${letter}" ${r.selections.includes(letter)?'checked':''}>${letter}</label>`).join('')}</div><p class="row-status ${r.uncertain?'uncertain':'small'}">${r.confirmed?(r.selections.length?'已识别 '+r.selections.join('、'):'未作答'):'标记较淡或单选多框，请核对'}</p><button class="confirm-row" data-row="${i}" ${r.confirmed?'hidden':''}>确认此题选择</button></div>`}).join('');
 $('rows').querySelectorAll('input').forEach(input=>input.onchange=()=>{const i=Number(input.dataset.row),r=scanResult.rows[i],q=byId.get(r.id),row=input.closest('.pdf-row');if(q.type==='single'&&input.checked)row.querySelectorAll('input').forEach(other=>{if(other!==input)other.checked=false});r.selections=[...row.querySelectorAll('input:checked')].map(e=>e.value);r.confirmed=true;row.querySelector('.row-status').textContent=r.selections.length?'已手动确认 '+r.selections.join('、'):'已确认留空';row.querySelector('.confirm-row').hidden=true;$('result').hidden=true;paintPending()});
 $('rows').querySelectorAll('.confirm-row').forEach(button=>button.onclick=()=>{const r=scanResult.rows[Number(button.dataset.row)],q=byId.get(r.id);if(q.type==='single'&&r.selections.length>1){button.closest('.pdf-row').querySelector('.row-status').textContent='单选只能保留一个选项，请调整勾选。';return}r.confirmed=true;button.hidden=true;button.closest('.pdf-row').querySelector('.row-status').textContent=r.selections.length?'已确认 '+r.selections.join('、'):'已确认留空';paintPending()});paintPending();
}
async function scan(){const file=$('answered-file').files[0];if(!file||busy){if(!file)$('scan-status').textContent='请先选择已作答的PDF。';return}busy=true;scanResult=null;$('scan').disabled=true;$('recognition').hidden=true;$('result').hidden=true;$('scan-status').className='';try{if(file.size>100*1048576)throw Error('文件超过100MB，请按套卷分批导出后作答。');await library();const original=$('original-file').files[0];if(original&&original.size>100*1048576)throw Error('原始文件超过100MB，请分批导出。');const bytes=new Uint8Array(await file.arrayBuffer()),originalBytes=original?new Uint8Array(await original.arrayBuffer()):undefined;let m=(await PdfNotebook.readManifest(bytes)).manifest;if(!m&&originalBytes)m=(await PdfNotebook.readManifest(originalBytes)).manifest;if(!m)m=await PdfNotebook.recoverManifest(bytes,{bankFor,onProgress:progress('scan-status')});scannedBank=await bankFor(m.subject);fileHash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('');scanResult=await PdfNotebook.scanPdf(bytes,{originalBytes,manifestOverride:m,bank:scannedBank,onProgress:progress('scan-status')});$('scan-status').textContent=`已识别 ${scanResult.rows.length} 道选择题。${m.recoveredFrom==='page-qr'?'已从页面二维码恢复题号，无需原始PDF。':''}简答题不自动判分。`;$('recognition').hidden=false;renderRows();}catch(e){$('scan-status').className='error';$('scan-status').textContent=e.message||'识别失败，请确认PDF格式。'}finally{busy=false;$('scan').disabled=false;if(scanResult)paintPending();updateSelection()}}
function grade(){if(!scanResult||scanResult.rows.some(r=>!r.confirmed))return;const byId=new Map(scannedBank.questions.map(q=>[q.id,q])),rows=scanResult.rows.map(r=>({...r,right:[...r.selections].sort().join(',')===[...byId.get(r.id).answer].sort().join(',')})),answered=rows.filter(r=>r.selections.length),right=answered.filter(r=>r.right).length,wrong=answered.length-right,blank=rows.length-answered.length;
 const totalPoints=rows.reduce((n,r)=>n+ChoiceScoring.max(byId.get(r.id)),0),earnedPoints=rows.reduce((n,r)=>n+ChoiceScoring.points(byId.get(r.id),r.selections),0);$('result').innerHTML=`<h3>PDF 批改结果</h3><p class="summary">得分 ${earnedPoints} / ${totalPoints} 分</p><p class="summary">已答 ${answered.length} · 答对 ${right} · 答错 ${wrong} · 未答 ${blank}<br>已答题正确率 ${answered.length?Math.round(right/answered.length*100)+'%':'—'}</p>`+rows.map(r=>{const q=byId.get(r.id);return `<article class="pdf-row" data-memory-id="${esc(q.id)}"><h4>第${q.paper}套 · 原题${q.number} <span class="${r.right?'success':'incorrect'}">${!r.selections.length?'未作答':r.right?'答对':ChoiceScoring.points(q,r.selections)>0?'少选':'答错'}</span></h4><p>本题得分：${ChoiceScoring.points(q,r.selections)} / ${ChoiceScoring.max(q)} 分</p><p>你的选择：${r.selections.join('、')||'—'}　正确答案：${q.answer.join('、')}</p><div class="pdf-explanation">${esc(q.explanation||'原卷未提供文字解析。')}${(q.explanationImages||[]).map(im=>`<img src="${esc(im.src)}" alt="${esc(im.alt)}">`).join('')}</div></article>`}).join('');$('result').hidden=false;$('result').querySelectorAll('[data-memory-id]').forEach(host=>Tianyu.mnemonicPanel(scannedBank.subject,host.dataset.memoryId,host));const record={id:fileHash,exportId:scanResult.manifest.id,subject:scannedBank.subject,date:new Date().toISOString(),answered,right,wrong,blank,earnedPoints,totalPoints,selections:rows.map(r=>({id:r.id,choices:r.selections,right:r.right}))};try{if(!Tianyu.recordPdf(record))throw Error('save_failed')}catch{$('result').insertAdjacentHTML('afterbegin','<p class="error">本机记录保存失败，当前结果仍可查看。</p>')}$('result').querySelectorAll('[data-memory-id]').forEach(host=>Tianyu.answerTools(scannedBank.subject,host.dataset.memoryId,host,{question:byId.get(host.dataset.memoryId)}));paintHistory();$('result').scrollIntoView({behavior:'smooth'})}
function paintHistory(){const records=Tianyu.pdfRecords();$('history').innerHTML=records.length?records.map(r=>`<div class="history-item"><strong>${esc(new Date(r.date).toLocaleString('zh-CN'))} · ${r.subject==='technical'?'安全技术':r.subject==='consolidation'?'技术巩固':'其他安全实务'} · PDF作答</strong><p>${Number.isFinite(r.earnedPoints)?'得分 '+r.earnedPoints+' / '+r.totalPoints+' 分 · ':''}已答 ${r.answered} · 答对 ${r.right} · 未全对 ${r.wrong} · 未答 ${r.blank}</p><button data-pdf-record="${r.id}">查看作答详情</button></div>`).join(''):'<p class="small">尚无 PDF 批改记录。</p>';document.querySelectorAll('[data-pdf-record]').forEach(b=>b.onclick=()=>viewRecord(b.dataset.pdfRecord))}
async function viewRecord(id){const r=Tianyu.pdfRecords().find(r=>r.id===id);if(!r)return;const box=$('history-detail');box.hidden=false;box.textContent='正在加载作答记录…';try{const bank=await bankFor(r.subject),byId=new Map(bank.questions.map(q=>[q.id,q]));box.innerHTML='<h3>PDF 作答详情</h3><p class="small">'+esc(new Date(r.date).toLocaleString('zh-CN'))+'</p>'+r.selections.map(row=>{const q=byId.get(row.id);if(!q)return '<p>题目 '+esc(row.id)+' 暂未加载。</p>';const pts=ChoiceScoring.points(q,row.choices);return `<article class="pdf-row" data-memory-id="${esc(q.id)}"><h4>第${q.paper}套 · 原题${q.number} · ${!row.choices.length?'未作答':row.right?'答对':pts>0?'少选':'答错'}</h4><p>${esc(q.stem)}</p>${(q.images||[]).map(im=>`<img src="${esc(im.src)}" alt="${esc(im.alt)}">`).join('')}<p>${Object.entries(q.options).map(([letter,text])=>esc(letter+'. '+text)+(q.optionImages?.[letter]||[]).map(im=>`<img src="${esc(im.src)}" alt="${esc(im.alt)}">`).join('')).join('<br>')}</p><p>你的选择：${row.choices.join('、')||'—'}　正确答案：${q.answer.join('、')}</p><p>本题得分：${pts} / ${ChoiceScoring.max(q)} 分</p><div class="pdf-explanation">${esc(q.explanation||'原卷未提供文字解析。')}${(q.explanationImages||[]).map(im=>`<img src="${esc(im.src)}" alt="${esc(im.alt)}">`).join('')}</div></article>`}).join('');box.querySelectorAll('[data-memory-id]').forEach(host=>{Tianyu.mnemonicPanel(r.subject,host.dataset.memoryId,host);Tianyu.answerTools(r.subject,host.dataset.memoryId,host,{question:byId.get(host.dataset.memoryId)})});}catch(e){box.textContent=e.message}box.scrollIntoView({behavior:'smooth'})}
window.addEventListener('tianyu-learning-change',()=>{paintHistory();updateSelection()});
 $('subject').value=['technical','practical','consolidation'].includes(new URLSearchParams(location.search).get('subject'))?new URLSearchParams(location.search).get('subject'):'technical';$('back').href='../'+location.hash;$('subject').onchange=changeSubject;$('retry-bank').onclick=changeSubject;['kind','scope','format'].forEach(id=>$(id).onchange=updateSelection);$('export').onclick=exportPdf;$('scan').onclick=scan;$('grade').onclick=grade;$('share-pdf').onclick=async()=>{try{await navigator.share({files:[pdfFile]})}catch(e){if(e.name!=='AbortError')$('export-status').textContent='分享未完成，也可点击“保存PDF”。'}};changeSubject();paintHistory();
})();
