(function(){
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),names={technical:'安全技术',practical:'其他安全实务'};
let data,visible=[],expanded=new Set(),revealed=new Set(),bankPromises={},sourceRequest=0,lastMemoryState="",shownLimit=40;
const params=new URLSearchParams(location.search),initial=params.get('subject');if(names[initial])$('subject').value=initial;
function paperOf(r){return Number(r.id.replace(/^p/,'').split('-')[0])}function numberOf(r){return r.id.split('-')[1]}function refLabel(r){return `${names[r.subject]} · 第${paperOf(r)}套原题${numberOf(r)}${r.part?" · 第"+r.part+"小问":""}`}
function state(c){return window.Tianyu?.memoryStatus(c.id)||'new'}
function refsFor(c){const subject=$('subject').value,paper=$('paper').value;return c.refs.filter(r=>(subject==='all'||r.subject===subject)&&(paper==='all'||paperOf(r)===Number(paper)))}
function updatePapers(){const old=$('paper').value,subject=$('subject').value,ps=[...new Set(data.cards.flatMap(c=>c.refs.filter(r=>subject==='all'||r.subject===subject).map(paperOf)))].sort((a,b)=>a-b);$('paper').innerHTML='<option value="all">全部套卷</option>'+ps.map(n=>`<option value="${n}">第${n}套</option>`).join('');$('paper').value=ps.includes(Number(old))?old:'all'}
function matches(c){const topic=$('topic').value,s=$('state').value,needle=$('search').value.trim().toLocaleLowerCase();const verification=$('verification').value;return (verification==='all'||(verification==='pending'?c.pending:!c.pending))&&refsFor(c).length&&(topic==='all'||topic===c.topic)&&(s==='all'||s===state(c))&&(!needle||[c.id,...c.refs.map(refLabel),c.title,c.chant,c.cue,c.topic,c.scope,...c.rules,...c.fixes.flatMap(f=>[f.wrong,f.correct])].join(' ').toLocaleLowerCase().includes(needle))}
function cardHTML(c){const shown=!$('recall').checked||revealed.has(c.id),open=expanded.has(c.id),current=state(c),label=current==='known'?'记住了':current==='review'?'还需记':'未标记',refs=refsFor(c);
return `<article class="memory-card" data-card="${esc(c.id)}"><div class="card-meta"><span>${esc(c.topic)}</span><span class="state-badge">${label}</span></div><h2>${esc(c.title)}</h2>${c.pending?'<p class="pending">待核对 · 仅记明确部分</p>':''}<p class="ref-label">${refs.map(refLabel).map(esc).join('；')}</p>${shown?`<div class="chant">${esc(c.chant)}</div>`:'<div class="recall-blank">先在心里说出关键规则，再揭晓。</div>'}<button class="details-toggle" data-action="reveal" aria-expanded="${shown&&open}">${!shown?'揭晓口诀与规则':open?'收起完整规则':'展开完整规则与订正'}</button><div class="rules" ${shown&&open?'':'hidden'}><h3>${c.pending?'已明确的记忆点与核对提示':c.basis==='规范条款核对'?'准确规则':'完整记忆点（原卷范围）'}</h3><ul>${c.rules.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>${c.scope?`<p class="scope">${esc(c.scope)}</p>`:''}${c.fixes.length?'<h3>容易记反的地方</h3>':''}${c.fixes.map(f=>`<div class="fix"><p class="wrong">易错说法：${esc(f.wrong)}</p><p>订正：${esc(f.correct)}</p></div>`).join('')}<h3>原题提问</h3><p class="cue">${esc(c.cue)}</p><h3>对应原题</h3><div class="source-links">${refs.map(r=>`<button data-action="source" data-subject="${r.subject}" data-id="${esc(r.id)}">${refLabel(r)}</button>`).join('')}</div><div class="basis"><p>${esc(c.basis)} · ${c.checked}</p>${c.sources.map(id=>{const s=data.sources[id];return `<p><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)}</a>${s.statusUrl?` · <a href="${esc(s.statusUrl)}" target="_blank" rel="noopener">官方标准状态</a>`:''}<br>${esc(s.note)}</p>`}).join('')}${!c.sources.length?'<p>依据为对应原题的卷末解析。请保留本题适用范围；这张卡未标为逐条规范核验。</p>':''}</div></div><div class="actions-row"><button data-action="review" class="mark-review" aria-pressed="${current==='review'}">还需记</button><button data-action="known" aria-pressed="${current==='known'}">记住了</button><button data-action="note">${window.Tianyu?.note('memory',c.id)?'编辑速记笔记':'写速记笔记'}</button>${$('recall').checked&&shown?'<button data-action="hide">重新回忆</button>':''}</div></article>`}
function memorySignature(){return JSON.stringify(data.cards.map(c=>[state(c),window.Tianyu?.note('memory',c.id)]))}
function render(){if(!data)return;lastMemoryState=memorySignature();visible=data.cards.filter(matches);$('cards').innerHTML=visible.slice(0,shownLimit).map(cardHTML).join('')||'<div class="load-error">没有符合条件的卡片。可以清除筛选，或者更换搜索词。</div>';$('more').hidden=visible.length<=shownLimit;$('more').textContent=`再看${Math.min(40,Math.max(0,visible.length-shownLimit))}张（还剩${Math.max(0,visible.length-shownLimit)}张）`;$('result-count').textContent=`已显示 ${Math.min(shownLimit,visible.length)} / 筛选到 ${visible.length} 张卡`; $('overview').textContent=`${data.cards.length} 张卡 · 覆盖 ${data.coverage.choices} 道选择题、${data.coverage.cases} 道案例/${data.coverage.parts}小问 · ${data.coverage.pendingCards}张待核对 · 记住了 ${data.cards.filter(c=>state(c)==='known').length} · 还需记 ${data.cards.filter(c=>state(c)==='review').length} · 核对日期 2026.10.07`}
async function bank(subject){if(!bankPromises[subject])bankPromises[subject]=(async()=>{const r=await fetch(`../pdf/${subject}.json`);if(!r.ok)throw Error('题目文件暂时加载失败');return r.json()})().catch(e=>{delete bankPromises[subject];throw e});return bankPromises[subject]}
function images(list){return (list||[]).map(img=>{const u=new URL(img.src,location.href);if(u.origin!==location.origin)return '';return `<img src="${esc(u.href)}" alt="${esc(img.alt||'原卷配图')}" loading="lazy">`}).join('')}
function textP(s,cls=''){return s?`<p class="${cls}">${esc(s)}</p>`:''}
async function source(subject,id){const request=++sourceRequest,d=$('source-dialog');$('source-title').textContent=`${names[subject]} · 第${paperOf({id})}套原题${numberOf({id})}`;$('source-content').innerHTML='<p role="status">正在加载对应原题…</p>';if(!d.open)d.showModal();try{const b=await bank(subject);if(request!==sourceRequest||!d.open)return;const q=b.questions.find(q=>q.id===id);if(!q)throw Error('未找到对应原题');const issue=data.issues.find(i=>i.subject===subject&&i.id===id),isShort=q.type==='short';$('source-content').innerHTML=`<section class="source-question"><p class="source-label">原题及卷末解析。速记的补充条件、订正与核验依据见卡片。</p>${issue?`<p class="scope">核对提示：${esc(issue.reason)}</p>`:''}${textP(q.material)}${images(q.materialImages)}${textP(q.stem)}${images(q.images)}${isShort?(q.parts||[]).map(p=>`<h3>第${p.number}小问</h3>${textP(p.prompt)}<details><summary>查看原卷参考答案</summary><div class="answer">${textP(p.referenceAnswer)}${images(p.referenceImages)}</div></details>`).join(''):`<ol>${Object.entries(q.options||{}).map(([k,v])=>`<li><strong>${esc(k)}.</strong> ${esc(v)}</li>`).join('')}</ol><details><summary>查看原卷答案与解析</summary><div class="answer">${textP('原卷答案：'+(q.answer||[]).join('、'))}${textP(q.explanation)}${images(q.explanationImages)}</div></details>`}<p><a data-learning-link href="../${subject}/${location.hash}">进入${names[subject]}题库练习 →</a></p></section>`;$('source-content').querySelectorAll('img').forEach(img=>img.onerror=()=>{const p=document.createElement('p');p.className='image-failure';p.textContent='配图加载失败，请联网后重新打开；离线使用前请下载完整离线包。';img.replaceWith(p)})}catch(e){if(request!==sourceRequest)return;$('source-content').innerHTML='<p role="alert">原题暂时加载失败。请联网后重试，或先下载完整离线包。</p><button id="retry-source">重试</button>';$('retry-source').onclick=()=>source(subject,id)}}
$('close-source').onclick=()=>{$('source-dialog').close();sourceRequest++};
$('cards').onclick=e=>{const b=e.target.closest('button[data-action]');if(!b)return;const article=b.closest('[data-card]'),id=article.dataset.card,c=data.cards.find(c=>c.id===id),action=b.dataset.action;if(action==='source'){source(b.dataset.subject,b.dataset.id);return}if(action==='note'){window.Tianyu.openNote('memory',id,c.title);return}if(action==='reveal'){if($('recall').checked&&!revealed.has(id)){revealed.add(id);expanded.add(id)}else if(expanded.has(id))expanded.delete(id);else expanded.add(id)}else if(action==='hide'){revealed.delete(id);expanded.delete(id)}else if(action==='review'||action==='known'){const saved=window.Tianyu.markMemory(id,state(c)===action?'new':action);if(!saved){$('result-count').textContent='保存失败，请保持页面打开。';return}}render();const fresh=document.querySelector(`[data-card="${id}"] [data-action="${action==='hide'?'reveal':action}"]`);fresh?.focus({preventScroll:true})};
async function load(){try{const r=await fetch('cards.json');if(!r.ok)throw Error('load');data=await r.json();if(!Array.isArray(data.cards)||!data.cards.length)throw Error('data');$('topic').innerHTML='<option value="all">全部知识点</option>'+[...new Set(data.cards.map(c=>c.topic))].map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('');updatePapers();$('notice').textContent=data.notice;$('issues').innerHTML=data.issues.map(i=>`<li>${refLabel(i)}：${esc(i.reason)}</li>`).join('');for(const id of ['subject','paper','topic','state','verification','recall'])$(id).onchange=()=>{shownLimit=40;if(id==='subject')updatePapers();if(id==='recall'){revealed.clear();expanded.clear()}render()};$('search').oninput=()=>{shownLimit=40;render()};$('more').onclick=()=>{shownLimit+=40;render()};$('reset').onclick=()=>{for(const id of ['subject','paper','topic','state','verification'])$(id).value='all';$('search').value='';shownLimit=40;updatePapers();render()};render();const target=params.get('card');if(data.cards.some(c=>c.id===target)){expanded.add(target);revealed.add(target);shownLimit=Math.max(40,data.cards.findIndex(c=>c.id===target)+1);render();document.querySelector(`[data-card="${target}"]`)?.scrollIntoView()}window.addEventListener('tianyu-learning-change',()=>{if(memorySignature()!==lastMemoryState)render()});$('note-dialog')?.addEventListener('close',render)}catch(e){$('overview').textContent='速记卡暂时加载失败';$('cards').innerHTML='<div class="load-error"><p>请检查网络后重试。若要断网复习，请先在首页下载完整离线包。</p><button id="retry-load">重新加载</button></div>';$('retry-load').onclick=load}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('../sw.js',{scope:'../'}).catch(()=>{});load();
})();
