(function(){
'use strict';
const $=id=>document.getElementById(id),T=window.Tianyu,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),text=s=>esc(String(s??'').replace(/\\n/g,'\n')),key='tianyu-recite-position-v1';
let data,rows=[],filtered=[],current='',revealed=false,lastSignature='';
const params=new URLSearchParams(location.search),label=r=>`第${r.q.paper}套 · 原题${r.q.number} · 第${r.p.number}小问`,state=r=>T.memoryStatus(r.c.id);
function persist(){try{localStorage.setItem(key,JSON.stringify({paper:$('paper').value,case:$('case').value,state:$('state').value,current,recall:$('recall').checked}))}catch{}}
function images(list){return (list||[]).map(img=>{const u=new URL(img.src,location.href);return u.origin===location.origin?`<img src="${esc(u.href)}" alt="${esc(img.alt||'原卷配图')}" loading="lazy">`:''}).join('')}
function updateCases(){const old=$('case').value,qs=[...new Map(rows.filter(r=>$('paper').value==='all'||r.q.paper===Number($('paper').value)).map(r=>[r.q.id,r.q])).values()];$('case').innerHTML='<option value="all">全部案例</option>'+qs.map(q=>`<option value="${q.id}">第${q.paper}套 · 原题${q.number} · ${esc(q.topic)}</option>`).join('');$('case').value=qs.some(q=>q.id===old)?old:'all'}
function selectRows(){filtered=rows.filter(r=>($('paper').value==='all'||r.q.paper===Number($('paper').value))&&($('case').value==='all'||r.q.id===$('case').value)&&($('state').value==='all'||state(r)===$('state').value));if(!filtered.some(r=>r.c.id===current))current=filtered[0]?.c.id||'';$('question').innerHTML=filtered.map(r=>`<option value="${r.c.id}">${label(r)} · ${esc(r.c.title)}</option>`).join('');$('question').value=current;$('question').disabled=!filtered.length;render()}
function signature(){const saved=T.counts('practical');return JSON.stringify(rows.map(r=>[state(r),T.note('practical',r.q.id+':'+r.p.number),saved[r.q.id+':'+r.p.number]||0]))}
function warning(r){if(r.c.id==='case-p2-28-1')return '原卷括注“市级”有误；本题较大特种设备事故按省级部门组织调查记忆，见下方订正及官方依据。';if(r.c.id==='case-p4-28-2')return '待核对：原卷未明确3号和6号容器分别对应4级还是5级，只记明确事实。';if(r.c.id==='case-p4-28-4')return '待核对：原卷对评价阶段及交接评价的表述含糊，不将该部分编成确定结论。';if(r.c.id==='case-p4-28-5')return '待核对：原卷只回答评价结论，未回答交接验收的不当之处；参考答案不完整。';return ''}
function render(){lastSignature=signature();const r=filtered.find(r=>r.c.id===current),i=filtered.indexOf(r);$('overview').textContent=`4套卷 · 12道案例 · ${rows.length}个小问 · 记住了 ${rows.filter(r=>state(r)==='known').length} · 还需记 ${rows.filter(r=>state(r)==='review').length}`;$('position').textContent=filtered.length?`第 ${i+1} / ${filtered.length} 小问`:'没有符合筛选的小问';$('prev').disabled=i<=0;$('next').disabled=i<0||i>=filtered.length-1;persist();if(!r){$('content').innerHTML='<p class="empty">没有符合条件的小问，可以清除筛选或更换记忆状态。</p>';return}
const s=state(r),shown=!$('recall').checked||revealed,w=warning(r),sources=r.c.sources.map(id=>data.sources[id]).filter(Boolean);
$('content').innerHTML=`<article class="recite-card" data-card="${r.c.id}"><p class="meta">${label(r)} · ${s==='known'?'记住了':s==='review'?'还需记':'未标记'}</p><h2>${text(r.p.prompt)}</h2><details class="case-material"><summary>查看案例材料</summary><div class="material">${text(r.q.material)}</div>${images(r.q.materialImages)}${images(r.q.images)}</details>${shown?`<section class="reference"><h3>原卷参考答案</h3>${w?`<p class="warning">${esc(w)}</p>`:''}<div class="answer">${text(r.p.referenceAnswer)}</div>${images(r.p.referenceImages)}</section>${r.c.id==='case-p2-28-1'?`<div class="correction"><strong>订正后记忆点</strong><ul>${r.c.rules.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></div>`:''}<section class="mnemonic"><h3>【助记口诀】${r.c.pending?' · 仅记明确部分':''}</h3><p><mark>${text(r.c.chant)}</mark></p></section><details class="mnemonic-hints"><summary>展开口诀关键词释义</summary><ul>${(r.c.mnemonicHints||[]).map(v=>`<li>${esc(v)}</li>`).join('')}</ul>${r.c.scope?`<p class="small">适用范围：${esc(r.c.scope)}</p>`:''}</details>${sources.length?`<div class="basis">${sources.map(s=>`<p><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)}</a><br>${esc(s.note)}</p>`).join('')}</div>`:''}`:'<div class="concealed"><p>先回忆得分点，再对照答案。</p><button id="reveal">对照答案与口诀</button></div>'}<div class="recite-actions"><button id="review" aria-pressed="${s==='review'}">还需记</button><button id="known" aria-pressed="${s==='known'}">记住了</button><button id="note">${T.note('practical',r.q.id+':'+r.p.number)?'编辑小问笔记':'写小问笔记'}</button>${$('recall').checked&&shown?'<button id="hide">重新背一遍</button>':''}</div></article>`;
if(shown)T.answerTools('practical',r.q.id,$('content').querySelector('.recite-card'),{question:r.q,part:r.p.number});
$('reveal')?.addEventListener('click',()=>{revealed=true;render()});$('hide')?.addEventListener('click',()=>{revealed=false;render()});for(const id of ['review','known'])$(id).onclick=()=>{if(!T.markMemory(r.c.id,s===id?'new':id)){$('position').textContent='保存失败，请保持页面打开。';return}selectRows();$(id)?.focus({preventScroll:true})};$('note').onclick=()=>T.openNote('practical',r.q.id+':'+r.p.number,label(r));$('content').querySelectorAll('img').forEach(img=>img.onerror=()=>{const p=document.createElement('p');p.className='image-failure';p.textContent='配图加载失败，请联网后重试或更新完整离线包。';img.replaceWith(p)})}
function move(d){const i=filtered.findIndex(r=>r.c.id===current),r=filtered[i+d];if(!r)return;current=r.c.id;revealed=false;selectRows()}
async function load(){try{const [bank,cards]=await Promise.all(['../pdf/practical.json?v=r23','../memory/cards.json?v=r23'].map(async url=>{const res=await fetch(url);if(!res.ok)throw Error('加载失败');return res.json()}));data=cards;rows=bank.questions.filter(q=>q.type==='short').flatMap(q=>q.parts.map(p=>({q,p,c:cards.cards.find(c=>c.id===`case-${q.id}-${p.number}`)})));if(!rows.length||rows.some(r=>!r.c))throw Error('缺少对应的背诵内容');$('paper').innerHTML='<option value="all">全部套卷</option>'+[...new Set(rows.map(r=>r.q.paper))].sort().map(n=>`<option value="${n}">第${n}套</option>`).join('');let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch{};for(const id of ['paper','state'])if([...$(id).options].some(o=>o.value===saved[id]))$(id).value=saved[id];updateCases();if([...$('case').options].some(o=>o.value===saved.case))$('case').value=saved.case;current=saved.current||'';$('recall').checked=!!saved.recall;
if(params.has('case')){const target=rows.find(r=>r.q.id===params.get('case')&&r.p.number===Number(params.get('part')||1));if(target){$('paper').value=String(target.q.paper);updateCases();$('case').value=target.q.id;$('state').value='all';current=target.c.id}}
for(const id of ['paper','case','state'])$(id).onchange=()=>{revealed=false;if(id==='paper')updateCases();selectRows()};$('question').onchange=()=>{current=$('question').value;revealed=false;render()};$('recall').onchange=()=>{revealed=false;render()};$('prev').onclick=()=>move(-1);$('next').onclick=()=>move(1);$('reset').onclick=()=>{for(const id of ['paper','state'])$(id).value='all';updateCases();$('case').value='all';revealed=false;selectRows()};selectRows();
}catch(e){$('content').innerHTML='<p role="alert">背诵内容暂时加载失败，请联网后重试；离线使用需先下载完整离线包。</p><button id="retry">重新加载</button>';$('overview').textContent='加载失败';$('retry').onclick=load}}
window.addEventListener('tianyu-learning-change',()=>{if(data&&signature()!==lastSignature&&!document.activeElement?.matches('[data-note-id]'))selectRows()});document.addEventListener('focusout',e=>{if(e.target.matches('[data-note-id]'))setTimeout(()=>{if(data&&signature()!==lastSignature&&!document.activeElement?.matches('[data-note-id]'))selectRows()},0)});document.addEventListener('close',e=>{if(e.target.id==='note-dialog'&&data)render()},true);load();if('serviceWorker'in navigator)navigator.serviceWorker.register('../sw.js',{scope:'../'}).catch(()=>{});
})();
